# Generated by Django 3.1 on 2020-08-18 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_auto_20200818_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockowned',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_owners', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='stockowned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
